repos:
  - repo: https://github.com/Trim21/pre-commit-hooks
    rev: 2cd566d7d05582364aaa111f4522efd33857346c  # frozen: v0.5.1
    hooks:
      - id: poetry-check-lock
      - id: find-trailing-comma

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 8fe62d14e0b4d7d845a7022c5c2c3ae41bdd3f26  # frozen: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
      - id: check-added-large-files  # check for file bigger than 500kb
      - id: check-yaml
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/asottile/pyupgrade
    rev: 0b37fd8e3b95981ff3d04b1351d2252a540e0cfc  # frozen: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/myint/autoflake
    rev: 7a53fdafc82c33f446915b60fcac947c51279260  # frozen: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/timothycrosley/isort
    rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: fc0be6eb1e2a96091e6f64009ee5e9081bf8b6c6  # frozen: 22.1.0
    hooks:
      - id: black

  - repo: https://github.com/adrienverge/yamllint
    rev: 058fef75598d1a9d9250487d91549abf379878e0  # frozen: v1.26.3
    hooks:
      - id: yamllint
