repos:
  - repo: https://github.com/Trim21/pre-commit-hooks
    rev: e4bd622f56f4cb289b7c15f6e9f03698afbc55d2  # frozen: v0.4.1
    hooks:
      - id: poetry-check-lock
      - id: find-trailing-comma

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539  # frozen: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
      - id: check-added-large-files  # check for file bigger than 500kb
      - id: check-yaml
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/asottile/pyupgrade
    rev: b6e103248fd97b04d2bea898b95d1d8776fece57  # frozen: v2.29.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/myint/autoflake
    rev: 7a53fdafc82c33f446915b60fcac947c51279260  # frozen: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/timothycrosley/isort
    rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 64c8be01f0cfedc94cb1c9ebd342ea77cafbb78a  # frozen: 21.10b0
    hooks:
      - id: black

  - repo: https://github.com/adrienverge/yamllint
    rev: 058fef75598d1a9d9250487d91549abf379878e0  # frozen: v1.26.3
    hooks:
      - id: yamllint
