name: ci
on:
  push:
    branches-ignore:
      - renovate/**
      - deepsource-fix-*
  pull_request: {}

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: ${{ matrix.python }}

      - uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
      - run: |
          uv sync --locked
          echo .venv/bin/ >> $GITHUB_PATH

      - name: test
        run: coverage run -m pytest

      - run: coverage xml

      - uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5
        if: ${{ startsWith(matrix.python, 'py') }}
        with:
          flags: ${{ matrix.python }}

      - uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5
        if: ${{ !startsWith(matrix.python, 'py') }}
        with:
          flags: py${{ matrix.python }}

  dist-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: "3.x"

      - run: pipx run build

      - run: pipx run twine check dist/*
