name: lint

on:
  push:
    branches-ignore:
      - renovate/**
      - deepsource-fix-*
  pull_request: {}

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - uses: astral-sh/setup-uv@v6
      - run: |
          uv sync --locked
          echo .venv/bin/ >> $GITHUB_PATH

      - uses: liskin/gh-problem-matcher-wrap@v3
        with:
          action: add
          linters: mypy

      - name: mypy
        run: mypy --show-column-numbers  anime_episode_parser

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - run: pip install pre-commit

      - uses: trim21/actions/pre-commit@master
