name: lint

on:
  push:
    branches-ignore:
      - renovate/**
      - deepsource-fix-*
  pull_request: {}

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.x"

      - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6
      - run: |
          uv sync --locked
          echo .venv/bin/ >> $GITHUB_PATH

      - uses: liskin/gh-problem-matcher-wrap@e7b7beaaafa52524748b31a381160759d68d61fb # v3
        with:
          action: add
          linters: mypy

      - name: mypy
        run: mypy --show-column-numbers  anime_episode_parser

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.x"

      - run: pip install pre-commit

      - uses: trim21/actions/pre-commit@master
